type CharMap = {
  x: number;
  y: number;
  width: number;
};

type FontMap = {
  cellWidth: number;
  charHeight: number;
  letters: Record<string | number, CharMap>;
};

const fontMaps: Record<string, FontMap> = {
  minecraftia: {
    cellWidth: 6,
    charHeight: 12,
    letters: {
      A: { x: 0, y: 0, width: 5 },
      B: { x: 1, y: 0, width: 5 },
      C: { x: 2, y: 0, width: 5 },
      D: { x: 3, y: 0, width: 5 },
      E: { x: 4, y: 0, width: 5 },
      F: { x: 5, y: 0, width: 5 },
      G: { x: 6, y: 0, width: 5 },
      H: { x: 7, y: 0, width: 5 },
      I: { x: 8, y: 0, width: 3 },
      J: { x: 9, y: 0, width: 5 },
      K: { x: 10, y: 0, width: 5 },
      L: { x: 11, y: 0, width: 5 },
      M: { x: 12, y: 0, width: 5 },
      N: { x: 13, y: 0, width: 5 },
      O: { x: 14, y: 0, width: 5 },
      P: { x: 15, y: 0, width: 5 },
      Q: { x: 16, y: 0, width: 5 },
      R: { x: 17, y: 0, width: 5 },
      S: { x: 18, y: 0, width: 5 },
      T: { x: 19, y: 0, width: 5 },
      U: { x: 0, y: 1, width: 5 },
      V: { x: 1, y: 1, width: 5 },
      W: { x: 2, y: 1, width: 5 },
      X: { x: 3, y: 1, width: 5 },
      Y: { x: 4, y: 1, width: 5 },
      Z: { x: 5, y: 1, width: 5 },
      Á: { x: 6, y: 1, width: 5 },
      À: { x: 7, y: 1, width: 5 },
      Ã: { x: 8, y: 1, width: 5 },
      Â: { x: 9, y: 1, width: 5 },
      É: { x: 10, y: 1, width: 5 },
      Ê: { x: 11, y: 1, width: 5 },
      Í: { x: 12, y: 1, width: 3 },
      Ó: { x: 13, y: 1, width: 5 },
      Ô: { x: 14, y: 1, width: 5 },
      Õ: { x: 15, y: 1, width: 5 },
      Ú: { x: 16, y: 1, width: 5 },
      Ç: { x: 17, y: 1, width: 5 },
      a: { x: 0, y: 2, width: 5 },
      b: { x: 1, y: 2, width: 5 },
      c: { x: 2, y: 2, width: 5 },
      d: { x: 3, y: 2, width: 5 },
      e: { x: 4, y: 2, width: 5 },
      f: { x: 5, y: 2, width: 4 },
      g: { x: 6, y: 2, width: 5 },
      h: { x: 7, y: 2, width: 5 },
      i: { x: 8, y: 2, width: 1 },
      j: { x: 9, y: 2, width: 5 },
      k: { x: 10, y: 2, width: 4 },
      l: { x: 11, y: 2, width: 2 },
      m: { x: 12, y: 2, width: 5 },
      n: { x: 13, y: 2, width: 5 },
      o: { x: 14, y: 2, width: 5 },
      p: { x: 15, y: 2, width: 5 },
      q: { x: 16, y: 2, width: 5 },
      r: { x: 17, y: 2, width: 5 },
      s: { x: 18, y: 2, width: 5 },
      t: { x: 19, y: 2, width: 3 },
      u: { x: 0, y: 3, width: 5 },
      v: { x: 1, y: 3, width: 5 },
      w: { x: 2, y: 3, width: 5 },
      x: { x: 3, y: 3, width: 5 },
      y: { x: 4, y: 3, width: 5 },
      z: { x: 5, y: 3, width: 5 },
      á: { x: 6, y: 3, width: 5 },
      à: { x: 7, y: 3, width: 5 },
      ã: { x: 8, y: 3, width: 5 },
      â: { x: 9, y: 3, width: 5 },
      é: { x: 10, y: 3, width: 5 },
      ê: { x: 11, y: 3, width: 5 },
      í: { x: 12, y: 3, width: 1 },
      ó: { x: 13, y: 3, width: 5 },
      ô: { x: 14, y: 3, width: 5 },
      õ: { x: 15, y: 3, width: 5 },
      ú: { x: 16, y: 3, width: 5 },
      ç: { x: 17, y: 3, width: 5 },
      "0": { x: 0, y: 4, width: 5 },
      "1": { x: 1, y: 4, width: 5 },
      "2": { x: 2, y: 4, width: 5 },
      "3": { x: 3, y: 4, width: 5 },
      "4": { x: 4, y: 4, width: 5 },
      "5": { x: 5, y: 4, width: 5 },
      "6": { x: 6, y: 4, width: 5 },
      "7": { x: 7, y: 4, width: 5 },
      "8": { x: 8, y: 4, width: 5 },
      "9": { x: 9, y: 4, width: 5 },
      "-": { x: 11, y: 4, width: 5 },
      "+": { x: 12, y: 4, width: 5 },
      "/": { x: 13, y: 4, width: 5 },
      "\\": { x: 14, y: 4, width: 5 },
      "<": { x: 15, y: 4, width: 4 },
      ">": { x: 16, y: 4, width: 4 },
      "!": { x: 17, y: 4, width: 1 },
      "?": { x: 18, y: 4, width: 5 },
      $: { x: 19, y: 4, width: 5 },
      ":": { x: 0, y: 5, width: 1 },
      ";": { x: 1, y: 5, width: 1 },
      ".": { x: 2, y: 5, width: 1 },
      ",": { x: 3, y: 5, width: 1 },
      '"': { x: 4, y: 5, width: 3 },
      "'": { x: 5, y: 5, width: 1 },
      "(": { x: 6, y: 5, width: 5 },
      ")": { x: 7, y: 5, width: 5 },
      "[": { x: 8, y: 5, width: 5 },
      "]": { x: 9, y: 5, width: 5 },
      "{": { x: 10, y: 5, width: 5 },
      "}": { x: 11, y: 5, width: 5 },
      "@": { x: 12, y: 5, width: 6 },
      "%": { x: 13, y: 5, width: 5 },

      " ": { x: 19, y: 5, width: 2 },
      "\n": { x: 19, y: 5, width: 0 },
    },
  },
  wcp: {
    cellWidth: 9,
    charHeight: 16,
    letters: {
      A: { x: 0, y: 0, width: 6 },
      B: { x: 1, y: 0, width: 7 },
      C: { x: 2, y: 0, width: 7 },
      D: { x: 3, y: 0, width: 7 },
      E: { x: 4, y: 0, width: 7 },
      F: { x: 5, y: 0, width: 7 },
      G: { x: 6, y: 0, width: 7 },
      H: { x: 7, y: 0, width: 6 },
      I: { x: 8, y: 0, width: 4 },
      J: { x: 9, y: 0, width: 7 },
      K: { x: 10, y: 0, width: 7 },
      L: { x: 11, y: 0, width: 7 },
      M: { x: 12, y: 0, width: 7 },
      N: { x: 13, y: 0, width: 7 },
      O: { x: 0, y: 1, width: 7 },
      P: { x: 1, y: 1, width: 7 },
      Q: { x: 2, y: 1, width: 7 },
      R: { x: 3, y: 1, width: 7 },
      S: { x: 4, y: 1, width: 6 },
      T: { x: 5, y: 1, width: 6 },
      U: { x: 6, y: 1, width: 6 },
      V: { x: 7, y: 1, width: 6 },
      W: { x: 8, y: 1, width: 7 },
      X: { x: 9, y: 1, width: 6 },
      Y: { x: 10, y: 1, width: 6 },
      Z: { x: 11, y: 1, width: 6 },
      "=": { x: 12, y: 1, width: 5 },
      Á: { x: 0, y: 2, width: 6 },
      À: { x: 1, y: 2, width: 6 },
      Â: { x: 3, y: 2, width: 6 },
      Ã: { x: 2, y: 2, width: 7 },
      É: { x: 4, y: 2, width: 7 },
      Ê: { x: 5, y: 2, width: 7 },
      Í: { x: 6, y: 2, width: 5 },
      Ó: { x: 7, y: 2, width: 7 },
      Ô: { x: 8, y: 2, width: 7 },
      Õ: { x: 9, y: 2, width: 7 },
      Ú: { x: 10, y: 2, width: 6 },
      Ç: { x: 11, y: 2, width: 6 },
      "@": { x: 12, y: 2, width: 7 },
      a: { x: 0, y: 3, width: 7 },
      b: { x: 1, y: 3, width: 7 },
      c: { x: 2, y: 3, width: 6 },
      d: { x: 3, y: 3, width: 7 },
      e: { x: 4, y: 3, width: 6 },
      f: { x: 5, y: 3, width: 6 },
      g: { x: 6, y: 3, width: 7 },
      h: { x: 7, y: 3, width: 7 },
      i: { x: 8, y: 3, width: 6 },
      j: { x: 9, y: 3, width: 6 },
      k: { x: 10, y: 3, width: 7 },
      l: { x: 11, y: 3, width: 6 },
      m: { x: 12, y: 3, width: 7 },
      n: { x: 13, y: 3, width: 6 },
      o: { x: 0, y: 4, width: 6 },
      p: { x: 1, y: 4, width: 7 },
      q: { x: 2, y: 4, width: 7 },
      r: { x: 3, y: 4, width: 7 },
      s: { x: 4, y: 4, width: 6 },
      t: { x: 5, y: 4, width: 6 },
      u: { x: 6, y: 4, width: 7 },
      v: { x: 7, y: 4, width: 6 },
      w: { x: 8, y: 4, width: 7 },
      x: { x: 9, y: 4, width: 7 },
      y: { x: 10, y: 4, width: 7 },
      z: { x: 11, y: 4, width: 6 },
      "<": { x: 12, y: 4, width: 6 },
      ">": { x: 13, y: 4, width: 6 },
      á: { x: 0, y: 5, width: 6 },
      à: { x: 1, y: 5, width: 6 },
      â: { x: 2, y: 5, width: 6 },
      ã: { x: 3, y: 5, width: 6 },
      é: { x: 4, y: 5, width: 6 },
      ê: { x: 5, y: 5, width: 6 },
      í: { x: 6, y: 5, width: 6 },
      ó: { x: 7, y: 5, width: 6 },
      ô: { x: 8, y: 5, width: 6 },
      õ: { x: 9, y: 5, width: 6 },
      ú: { x: 10, y: 5, width: 6 },
      ç: { x: 11, y: 5, width: 6 },
      "/": { x: 12, y: 5, width: 8 },
      "\\": { x: 13, y: 5, width: 8 },
      "0": { x: 0, y: 6, width: 7 },
      "1": { x: 1, y: 6, width: 6 },
      "2": { x: 2, y: 6, width: 6 },
      "3": { x: 3, y: 6, width: 6 },
      "4": { x: 4, y: 6, width: 7 },
      "5": { x: 5, y: 6, width: 6 },
      "6": { x: 6, y: 6, width: 6 },
      "7": { x: 7, y: 6, width: 6 },
      "8": { x: 8, y: 6, width: 6 },
      "9": { x: 9, y: 6, width: 6 },
      "-": { x: 10, y: 6, width: 6 },
      "+": { x: 11, y: 6, width: 6 },
      "*": { x: 12, y: 6, width: 7 },
      "^": { x: 13, y: 6, width: 7 },
      "!": { x: 0, y: 7, width: 4 },
      "?": { x: 1, y: 7, width: 6 },
      ":": { x: 2, y: 7, width: 2 },
      ";": { x: 3, y: 7, width: 3 },
      ".": { x: 4, y: 7, width: 2 },
      ",": { x: 5, y: 7, width: 3 },
      '"': { x: 6, y: 7, width: 6 },
      "'": { x: 7, y: 7, width: 6 },
      "(": { x: 8, y: 7, width: 6 },
      ")": { x: 9, y: 7, width: 6 },
      "[": { x: 10, y: 7, width: 6 },
      "]": { x: 11, y: 7, width: 6 },
      "{": { x: 12, y: 7, width: 6 },
      "}": { x: 13, y: 7, width: 6 },

      " ": { x: 19, y: 7, width: 2 },
      "\n": { x: 19, y: 7, width: 0 },
    },
  },
};

export default fontMaps;
